project:
  type: website
  output-dir: docs

website:
  title: "LVM"
  site-url: https://lvallejomendez.github.io/
  description: "data science, machine learning and technology"
  reader-mode: true
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - text: More
        menu:
          - resume.qmd
    right:
      - icon: linkedin
        href: https://es.linkedin.com/in/luisvallejomendez
      - icon: github 
        href: "https://github.com/lvallejomendez"
  
  page-footer: 
    left: "Copyright 2022, Luis Vallejo MÃ©ndez"
    center:
      - href: index.qmd
        text: LVM
    right: 
      - icon: linkedin
        href: https://es.linkedin.com/in/luisvallejomendez
      - icon: github 
        href: https://github.com/lvallejomendez
      - icon: award-fill
        href: https://www.credly.com/users/luis-vallejo/badges?sort=-state_updated_at&page=1

format:
  html:
    theme: slate
    css: styles.css
    toc: true